language: node_js
node_js:
  - 8
script: echo "nothing to see here, move along"
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master

# blocklist version commits
branches:
  except:
    - /^v[0-9]/
